/* eslint-disable max-lines */
import type { RoutineWithItems } from "@/features/routines/types/routine-with-items";

import { ROUTINE_ITEM_TYPE } from "@/features/routines/types/routine-item";

import { COLOR_NAME } from "@/features/colors/types/colors";

export const routines: RoutineWithItems[] = [
  {
    id: 1,
    created_at: "2025-04-10T18:23:05.736Z",
    hidden_at: null,
    name: "Morning",
    start_time: "06:30",
    updated_at: "2025-04-10T18:23:05.736Z",
    user_id: 1,
    routine_items: [
      {
        id: 1,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Make Bed",
        item_exp_seconds: 180,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 1,
      },
      {
        id: 2,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Bathroom",
        item_exp_seconds: 300,
        category_name: "Necessary",
        category_color: COLOR_NAME.AMBER,
        position: 2,
      },
      {
        id: 3,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Weight",
        item_exp_seconds: 120,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 3,
      },
      {
        id: 4,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Reply",
        item_exp_seconds: 120,
        category_name: "Necessary",
        category_color: COLOR_NAME.AMBER,
        position: 4,
      },
      {
        id: 135,
        type: ROUTINE_ITEM_TYPE.ROUTINE,
        item_name: "Quick Stretch Routine",
        item_exp_seconds: 600,
        category_name: null,
        category_color: null,
        position: 5,
      },
      {
        id: 133,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Dishes",
        item_exp_seconds: 420,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 6,
      },
      {
        id: 134,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Stretch",
        item_exp_seconds: 300,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 7,
      },
    ],
  },
  {
    id: 2,
    created_at: "2025-04-10T19:18:23.972Z",
    hidden_at: null,
    name: "Workout",
    start_time: "18:50",
    updated_at: "2025-04-10T19:18:23.972Z",
    user_id: 1,
    routine_items: [
      {
        id: 5,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "PreWorkout",
        item_exp_seconds: 300,
        category_name: "Necessary",
        category_color: COLOR_NAME.AMBER,
        position: 1,
      },
      {
        id: 6,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Stretch",
        item_exp_seconds: 300,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 2,
      },
      {
        id: 7,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Workout",
        item_exp_seconds: 4500,
        category_name: "Productive",
        category_color: COLOR_NAME.BLUE,
        position: 3,
      },
      {
        id: 8,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "PostWorkout",
        item_exp_seconds: 300,
        category_name: "Necessary",
        category_color: COLOR_NAME.AMBER,
        position: 4,
      },
      {
        id: 9,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Snack",
        item_exp_seconds: 600,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 5,
      },
      {
        id: 34,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Brush Teeth",
        item_exp_seconds: 420,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 6,
      },
      {
        id: 136,
        type: ROUTINE_ITEM_TYPE.ROUTINE,
        item_name: "Evening Cooldown Routine",
        item_exp_seconds: 900,
        category_name: null,
        category_color: null,
        position: 7,
      },
    ],
  },
  {
    id: 3,
    created_at: "2025-04-10T19:18:23.972Z",
    hidden_at: null,
    name: "Swimming",
    start_time: null,
    updated_at: "2025-04-10T19:18:23.972Z",
    user_id: 1,
    routine_items: [],
  },
  {
    id: 6,
    created_at: "2025-04-13T17:32:36.646Z",
    hidden_at: null,
    name: "Shower",
    start_time: "04:00",
    updated_at: "2025-04-13T17:32:36.646Z",
    user_id: 1,
    routine_items: [
      {
        id: 21,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Bathroom",
        item_exp_seconds: 300,
        category_name: "Necessary",
        category_color: COLOR_NAME.AMBER,
        position: 1,
      },
      {
        id: 22,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Shower",
        item_exp_seconds: 1200,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 2,
      },
      {
        id: 23,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Chores",
        item_exp_seconds: 600,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 3,
      },
    ],
  },
  {
    id: 7,
    created_at: "2025-04-15T10:00:00.000Z",
    hidden_at: "2025-12-20T15:30:00.000Z",
    name: "Old Routine (Hidden)",
    start_time: "07:00",
    updated_at: "2025-12-20T15:30:00.000Z",
    user_id: 1,
    routine_items: [
      {
        id: 24,
        type: ROUTINE_ITEM_TYPE.ACTIVITY,
        item_name: "Meditation",
        item_exp_seconds: 600,
        category_name: "Wellness",
        category_color: COLOR_NAME.EMERALD,
        position: 1,
      },
    ],
  },
  {
    id: 8,
    created_at: "2025-05-01T12:00:00.000Z",
    hidden_at: "2026-01-10T10:00:00.000Z",
    name: "Archived Evening Routine",
    start_time: "20:00",
    updated_at: "2026-01-10T10:00:00.000Z",
    user_id: 1,
    routine_items: [],
  },
];
