/* eslint-disable max-lines */
import { Routine } from "@/features/routines/types/routine";

export const routines: Routine[] = [
  {
    id: 1,
    created_at: "2025-04-10T18:23:05.736Z",
    name: "Morning",
    updated_at: "2025-04-10T18:23:05.736Z",
    hidden_at: null,
    user_id: 1,
    activities: [
      {
        id: 1,
        activity_id: 54,
        activity_name: "Make Bed",
        activity_exp_seconds: 180,
        category_name: "Wellness",
        category_color: "emerald",
        position: 1,
      },
      {
        id: 2,
        activity_id: 36,
        activity_name: "Bathroom",
        activity_exp_seconds: 300,
        category_name: "Necessary",
        category_color: "amber",
        position: 2,
      },
      {
        id: 3,
        activity_id: 74,
        activity_name: "Weight",
        activity_exp_seconds: 120,
        category_name: "Wellness",
        category_color: "emerald",
        position: 3,
      },
      {
        id: 4,
        activity_id: 61,
        activity_name: "Reply",
        activity_exp_seconds: 120,
        category_name: "Necessary",
        category_color: "amber",
        position: 4,
      },
      {
        id: 133,
        activity_id: 49,
        activity_name: "Dishes",
        activity_exp_seconds: 420,
        category_name: "Wellness",
        category_color: "emerald",
        position: 6,
      },
      {
        id: 134,
        activity_id: 68,
        activity_name: "Stretch",
        activity_exp_seconds: 300,
        category_name: "Wellness",
        category_color: "emerald",
        position: 7,
      },
    ],
  },
  {
    id: 2,
    created_at: "2025-04-10T19:18:23.972Z",
    name: "Workout",
    updated_at: "2025-04-10T19:18:23.972Z",
    hidden_at: null,
    user_id: 1,
    activities: [
      {
        id: 5,
        activity_id: 57,
        activity_name: "PreWorkout",
        activity_exp_seconds: 300,
        category_name: "Necessary",
        category_color: "amber",
        position: 1,
      },
      {
        id: 6,
        activity_id: 68,
        activity_name: "Stretch",
        activity_exp_seconds: 300,
        category_name: "Wellness",
        category_color: "emerald",
        position: 2,
      },
      {
        id: 7,
        activity_id: 1,
        activity_name: "Workout",
        activity_exp_seconds: 4500,
        category_name: "Productive",
        category_color: "blue",
        position: 3,
      },
      {
        id: 8,
        activity_id: 56,
        activity_name: "PostWorkout",
        activity_exp_seconds: 300,
        category_name: "Necessary",
        category_color: "amber",
        position: 4,
      },
      {
        id: 9,
        activity_id: 67,
        activity_name: "Snack",
        activity_exp_seconds: 600,
        category_name: "Wellness",
        category_color: "emerald",
        position: 5,
      },
      {
        id: 34,
        activity_id: 39,
        activity_name: "Brush Teeth",
        activity_exp_seconds: 420,
        category_name: "Wellness",
        category_color: "emerald",
        position: 6,
      },
    ],
  },
  {
    id: 3,
    created_at: "2025-04-10T19:18:23.972Z",
    name: "Swimming",
    updated_at: "2025-04-10T19:18:23.972Z",
    hidden_at: null,
    user_id: 1,
    activities: [],
  },
  {
    id: 6,
    created_at: "2025-04-13T17:32:36.646Z",
    name: "Shower",
    updated_at: "2025-04-13T17:32:36.646Z",
    hidden_at: null,
    user_id: 1,
    activities: [
      {
        id: 21,
        activity_id: 36,
        activity_name: "Bathroom",
        activity_exp_seconds: 300,
        category_name: "Necessary",
        category_color: "amber",
        position: 1,
      },
      {
        id: 22,
        activity_id: 66,
        activity_name: "Shower",
        activity_exp_seconds: 1200,
        category_name: "Wellness",
        category_color: "emerald",
        position: 2,
      },
      {
        id: 23,
        activity_id: 44,
        activity_name: "Chores",
        activity_exp_seconds: 600,
        category_name: "Wellness",
        category_color: "emerald",
        position: 3,
      },
    ],
  },
];
