import { Color } from "../types/color";

export const colors: Color[] = [
  {
    id: 1,
    name: "white",
    bgClass: "bg-white",
    textClass: "text-black",
    borderClass: "border-black",
  },
  {
    id: 2,
    name: "rose",
    bgClass: "bg-rose-300",
    textClass: "text-rose-950",
    borderClass: "border-rose-600",
  },
  {
    id: 3,
    name: "amber",
    bgClass: "bg-amber-300",
    textClass: "text-amber-950",
    borderClass: "border-amber-700",
  },
  {
    id: 4,
    name: "emerald",
    bgClass: "bg-emerald-300",
    textClass: "text-emerald-950",
    borderClass: "border-emerald-700",
  },
  {
    id: 5,
    name: "teal",
    bgClass: "bg-teal-300",
    textClass: "text-teal-950",
    borderClass: "border-teal-700",
  },
  {
    id: 6,
    name: "cyan",
    bgClass: "bg-cyan-300",
    textClass: "text-cyan-950",
    borderClass: "border-cyan-700",
  },
  {
    id: 7,
    name: "sky",
    bgClass: "bg-sky-300",
    textClass: "text-sky-950",
    borderClass: "border-sky-700",
  },
  {
    id: 8,
    name: "blue",
    bgClass: "bg-blue-300",
    textClass: "text-blue-950",
    borderClass: "border-blue-700",
  },
  {
    id: 9,
    name: "indigo",
    bgClass: "bg-indigo-300",
    textClass: "text-indigo-950",
    borderClass: "border-indigo-700",
  },
  {
    id: 10,
    name: "violet",
    bgClass: "bg-violet-300",
    textClass: "text-violet-950",
    borderClass: "border-violet-700",
  },
  {
    id: 11,
    name: "purple",
    bgClass: "bg-purple-300",
    textClass: "text-purple-950",
    borderClass: "border-purple-700",
  },
  {
    id: 12,
    name: "fuchsia",
    bgClass: "bg-fuchsia-300",
    textClass: "text-fuchsia-950",
    borderClass: "border-fuchsia-700",
  },
  {
    id: 13,
    name: "pink",
    bgClass: "bg-pink-300",
    textClass: "text-pink-950",
    borderClass: "border-pink-700",
  },
  {
    id: 14,
    name: "rose",
    bgClass: "bg-rose-300",
    textClass: "text-rose-950",
    borderClass: "border-rose-700",
  },
];
