import type { Color } from "../types/color";

import { COLOR_NAME } from "@/features/colors/types/colors";

export const colors: Color[] = [
  {
    id: 1,
    name: COLOR_NAME.WHITE,
    bgClass: "bg-white",
    textClass: "text-black",
    borderClass: "border-black",
    fillClass: "fill-black",
  },
  {
    id: 2,
    name: COLOR_NAME.ROSE,
    bgClass: "bg-rose-300",
    textClass: "text-rose-950",
    borderClass: "border-rose-600",
    fillClass: "fill-rose-600",
  },
  {
    id: 3,
    name: COLOR_NAME.AMBER,
    bgClass: "bg-amber-300",
    textClass: "text-amber-950",
    borderClass: "border-amber-700",
    fillClass: "fill-amber-600",
  },
  {
    id: 4,
    name: COLOR_NAME.EMERALD,
    bgClass: "bg-emerald-300",
    textClass: "text-emerald-950",
    borderClass: "border-emerald-700",
    fillClass: "fill-emerald-600",
  },
  {
    id: 5,
    name: COLOR_NAME.TEAL,
    bgClass: "bg-teal-300",
    textClass: "text-teal-950",
    borderClass: "border-teal-700",
    fillClass: "fill-teal-600",
  },
  {
    id: 6,
    name: COLOR_NAME.CYAN,
    bgClass: "bg-cyan-300",
    textClass: "text-cyan-950",
    borderClass: "border-cyan-700",
    fillClass: "fill-cyan-600",
  },
  {
    id: 7,
    name: COLOR_NAME.SKY,
    bgClass: "bg-sky-300",
    textClass: "text-sky-950",
    borderClass: "border-sky-700",
    fillClass: "fill-sky-600",
  },
  {
    id: 8,
    name: COLOR_NAME.BLUE,
    bgClass: "bg-blue-300",
    textClass: "text-blue-950",
    borderClass: "border-blue-700",
    fillClass: "fill-blue-600",
  },
  {
    id: 9,
    name: COLOR_NAME.INDIGO,
    bgClass: "bg-indigo-300",
    textClass: "text-indigo-950",
    borderClass: "border-indigo-700",
    fillClass: "fill-indigo-600",
  },
  {
    id: 10,
    name: COLOR_NAME.VIOLET,
    bgClass: "bg-violet-300",
    textClass: "text-violet-950",
    borderClass: "border-violet-700",
    fillClass: "fill-violet-600",
  },
  {
    id: 11,
    name: COLOR_NAME.PURPLE,
    bgClass: "bg-purple-300",
    textClass: "text-purple-950",
    borderClass: "border-purple-700",
    fillClass: "fill-purple-600",
  },
  {
    id: 12,
    name: COLOR_NAME.FUCHSIA,
    bgClass: "bg-fuchsia-300",
    textClass: "text-fuchsia-950",
    borderClass: "border-fuchsia-700",
    fillClass: "fill-fuchsia-600",
  },
  {
    id: 13,
    name: COLOR_NAME.PINK,
    bgClass: "bg-pink-300",
    textClass: "text-pink-950",
    borderClass: "border-pink-700",
    fillClass: "fill-pink-600",
  },
  {
    id: 14,
    name: COLOR_NAME.ROSE,
    bgClass: "bg-rose-300",
    textClass: "text-rose-950",
    borderClass: "border-rose-700",
    fillClass: "fill-rose-600",
  },
];
