const API_V1_URL = `${import.meta.env.VITE_API_URL}/v1`;

export const apiRoutes = {
  activities: `${API_V1_URL}/activities`,
  activity: `${API_V1_URL}/activities/:activityId`,
  activityOptions: `${API_V1_URL}/activities/*`,
  categories: `${API_V1_URL}/categories`,
  category: `${API_V1_URL}/categories/:categoryId`,
  deleteScheduledTasks: `${API_V1_URL}/tasks/delete_scheduled`,
  me: `${API_V1_URL}/me`,
  protected: `${API_V1_URL}/protected`,
  refreshSession: `${API_V1_URL}/session/refresh`,
  routine: `${API_V1_URL}/routines/:routineId`,
  routineApply: `${API_V1_URL}/routines/:routineId/apply`,
  routineHide: `${API_V1_URL}/routines/:routineId/hide`,
  routineItem: `${API_V1_URL}/routines/:routineId/items/:activityId`,
  routineItems: `${API_V1_URL}/routines/:routineId/items`,
  routines: `${API_V1_URL}/routines`,
  routineUnhide: `${API_V1_URL}/routines/:routineId/unhide`,
  session: `${API_V1_URL}/session`,
  straggler: `${API_V1_URL}/straggler`,
  task: `${API_V1_URL}/tasks/:taskId`,
  taskMove: `${API_V1_URL}/tasks/move_drag`,
  taskSpanDeletions: `${API_V1_URL}/tasks/span_deletions`,
  taskSpanMoves: `${API_V1_URL}/tasks/span_moves`,
  tasks: `${API_V1_URL}/tasks`,
  test: `${API_V1_URL}/test`,
  userPreferences: `${API_V1_URL}/user_preferences`,
} as const;
