/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as _protectedRouteRouteImport } from "./routes/__protected/route";
import { Route as _protectedIndexRouteImport } from "./routes/__protected/index";
import { Route as _protectedTimerRouteRouteImport } from "./routes/__protected/timer/route";
import { Route as _protectedSettingsRouteRouteImport } from "./routes/__protected/settings/route";
import { Route as _protectedRoutinesRouteRouteImport } from "./routes/__protected/routines/route";
import { Route as _protectedHistoryRouteRouteImport } from "./routes/__protected/history/route";
import { Route as _protectedActivitiesRouteRouteImport } from "./routes/__protected/activities/route";
import { Route as _protectedTimerIndexRouteImport } from "./routes/__protected/timer/index";
import { Route as _protectedSettingsIndexRouteImport } from "./routes/__protected/settings/index";
import { Route as _protectedExcelIndexRouteImport } from "./routes/__protected/excel/index";
import { Route as _protectedTimerNewRouteImport } from "./routes/__protected/timer/new";
import { Route as _protectedSettingsNotificationsRouteImport } from "./routes/__protected/settings/notifications";
import { Route as _protectedSettingsAccountRouteImport } from "./routes/__protected/settings/account";
import { Route as _protectedRoutinesNewRouteImport } from "./routes/__protected/routines/new";
import { Route as _protectedHistoryNewRouteImport } from "./routes/__protected/history/new";
import { Route as _protectedActivitiesNewRouteImport } from "./routes/__protected/activities/new";
import { Route as _protectedTimerTaskIdRouteRouteImport } from "./routes/__protected/timer/$taskId/route";
import { Route as _protectedSettingsCategoriesRouteRouteImport } from "./routes/__protected/settings/categories/route";
import { Route as _protectedRoutinesRoutineIdRouteRouteImport } from "./routes/__protected/routines/$routineId/route";
import { Route as _protectedHistoryTaskIdRouteRouteImport } from "./routes/__protected/history/$taskId/route";
import { Route as _protectedActivitiesActivityIdRouteRouteImport } from "./routes/__protected/activities/$activityId/route";
import { Route as _protectedHistoryTaskIdIndexRouteImport } from "./routes/__protected/history/$taskId/index";
import { Route as _protectedActivitiesActivityIdIndexRouteImport } from "./routes/__protected/activities/$activityId/index";
import { Route as _protectedTimerTaskIdEditRouteImport } from "./routes/__protected/timer/$taskId/edit";
import { Route as _protectedSettingsCategoriesNewRouteImport } from "./routes/__protected/settings/categories/new";
import { Route as _protectedRoutinesRoutineIdEditRouteImport } from "./routes/__protected/routines/$routineId/edit";
import { Route as _protectedRoutinesRoutineIdDeleteRouteImport } from "./routes/__protected/routines/$routineId/delete";
import { Route as _protectedActivitiesActivityIdEditRouteImport } from "./routes/__protected/activities/$activityId/edit";
import { Route as _protectedActivitiesActivityIdDeleteRouteImport } from "./routes/__protected/activities/$activityId/delete";
import { Route as _protectedSettingsCategoriesCategoryIdRouteRouteImport } from "./routes/__protected/settings/categories/$categoryId/route";
import { Route as _protectedSettingsCategoriesCategoryIdEditRouteImport } from "./routes/__protected/settings/categories/$categoryId/edit";
import { Route as _protectedSettingsCategoriesCategoryIdDeleteRouteImport } from "./routes/__protected/settings/categories/$categoryId/delete";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const _protectedRouteRoute = _protectedRouteRouteImport.update({
  id: "/__protected",
  getParentRoute: () => rootRouteImport,
} as any);
const _protectedIndexRoute = _protectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => _protectedRouteRoute,
} as any);
const _protectedTimerRouteRoute = _protectedTimerRouteRouteImport.update({
  id: "/timer",
  path: "/timer",
  getParentRoute: () => _protectedRouteRoute,
} as any);
const _protectedSettingsRouteRoute = _protectedSettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => _protectedRouteRoute,
} as any);
const _protectedRoutinesRouteRoute = _protectedRoutinesRouteRouteImport.update({
  id: "/routines",
  path: "/routines",
  getParentRoute: () => _protectedRouteRoute,
} as any);
const _protectedHistoryRouteRoute = _protectedHistoryRouteRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => _protectedRouteRoute,
} as any);
const _protectedActivitiesRouteRoute =
  _protectedActivitiesRouteRouteImport.update({
    id: "/activities",
    path: "/activities",
    getParentRoute: () => _protectedRouteRoute,
  } as any);
const _protectedTimerIndexRoute = _protectedTimerIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => _protectedTimerRouteRoute,
} as any);
const _protectedSettingsIndexRoute = _protectedSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => _protectedSettingsRouteRoute,
} as any);
const _protectedExcelIndexRoute = _protectedExcelIndexRouteImport.update({
  id: "/excel/",
  path: "/excel/",
  getParentRoute: () => _protectedRouteRoute,
} as any);
const _protectedTimerNewRoute = _protectedTimerNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => _protectedTimerRouteRoute,
} as any);
const _protectedSettingsNotificationsRoute =
  _protectedSettingsNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => _protectedSettingsRouteRoute,
  } as any);
const _protectedSettingsAccountRoute =
  _protectedSettingsAccountRouteImport.update({
    id: "/account",
    path: "/account",
    getParentRoute: () => _protectedSettingsRouteRoute,
  } as any);
const _protectedRoutinesNewRoute = _protectedRoutinesNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => _protectedRoutinesRouteRoute,
} as any);
const _protectedHistoryNewRoute = _protectedHistoryNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => _protectedHistoryRouteRoute,
} as any);
const _protectedActivitiesNewRoute = _protectedActivitiesNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => _protectedActivitiesRouteRoute,
} as any);
const _protectedTimerTaskIdRouteRoute =
  _protectedTimerTaskIdRouteRouteImport.update({
    id: "/$taskId",
    path: "/$taskId",
    getParentRoute: () => _protectedTimerRouteRoute,
  } as any);
const _protectedSettingsCategoriesRouteRoute =
  _protectedSettingsCategoriesRouteRouteImport.update({
    id: "/categories",
    path: "/categories",
    getParentRoute: () => _protectedSettingsRouteRoute,
  } as any);
const _protectedRoutinesRoutineIdRouteRoute =
  _protectedRoutinesRoutineIdRouteRouteImport.update({
    id: "/$routineId",
    path: "/$routineId",
    getParentRoute: () => _protectedRoutinesRouteRoute,
  } as any);
const _protectedHistoryTaskIdRouteRoute =
  _protectedHistoryTaskIdRouteRouteImport.update({
    id: "/$taskId",
    path: "/$taskId",
    getParentRoute: () => _protectedHistoryRouteRoute,
  } as any);
const _protectedActivitiesActivityIdRouteRoute =
  _protectedActivitiesActivityIdRouteRouteImport.update({
    id: "/$activityId",
    path: "/$activityId",
    getParentRoute: () => _protectedActivitiesRouteRoute,
  } as any);
const _protectedHistoryTaskIdIndexRoute =
  _protectedHistoryTaskIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => _protectedHistoryTaskIdRouteRoute,
  } as any);
const _protectedActivitiesActivityIdIndexRoute =
  _protectedActivitiesActivityIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => _protectedActivitiesActivityIdRouteRoute,
  } as any);
const _protectedTimerTaskIdEditRoute =
  _protectedTimerTaskIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => _protectedTimerTaskIdRouteRoute,
  } as any);
const _protectedSettingsCategoriesNewRoute =
  _protectedSettingsCategoriesNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => _protectedSettingsCategoriesRouteRoute,
  } as any);
const _protectedRoutinesRoutineIdEditRoute =
  _protectedRoutinesRoutineIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => _protectedRoutinesRoutineIdRouteRoute,
  } as any);
const _protectedRoutinesRoutineIdDeleteRoute =
  _protectedRoutinesRoutineIdDeleteRouteImport.update({
    id: "/delete",
    path: "/delete",
    getParentRoute: () => _protectedRoutinesRoutineIdRouteRoute,
  } as any);
const _protectedActivitiesActivityIdEditRoute =
  _protectedActivitiesActivityIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => _protectedActivitiesActivityIdRouteRoute,
  } as any);
const _protectedActivitiesActivityIdDeleteRoute =
  _protectedActivitiesActivityIdDeleteRouteImport.update({
    id: "/delete",
    path: "/delete",
    getParentRoute: () => _protectedActivitiesActivityIdRouteRoute,
  } as any);
const _protectedSettingsCategoriesCategoryIdRouteRoute =
  _protectedSettingsCategoriesCategoryIdRouteRouteImport.update({
    id: "/$categoryId",
    path: "/$categoryId",
    getParentRoute: () => _protectedSettingsCategoriesRouteRoute,
  } as any);
const _protectedSettingsCategoriesCategoryIdEditRoute =
  _protectedSettingsCategoriesCategoryIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => _protectedSettingsCategoriesCategoryIdRouteRoute,
  } as any);
const _protectedSettingsCategoriesCategoryIdDeleteRoute =
  _protectedSettingsCategoriesCategoryIdDeleteRouteImport.update({
    id: "/delete",
    path: "/delete",
    getParentRoute: () => _protectedSettingsCategoriesCategoryIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/login": typeof LoginRoute;
  "/activities": typeof _protectedActivitiesRouteRouteWithChildren;
  "/history": typeof _protectedHistoryRouteRouteWithChildren;
  "/routines": typeof _protectedRoutinesRouteRouteWithChildren;
  "/settings": typeof _protectedSettingsRouteRouteWithChildren;
  "/timer": typeof _protectedTimerRouteRouteWithChildren;
  "/": typeof _protectedIndexRoute;
  "/activities/$activityId": typeof _protectedActivitiesActivityIdRouteRouteWithChildren;
  "/history/$taskId": typeof _protectedHistoryTaskIdRouteRouteWithChildren;
  "/routines/$routineId": typeof _protectedRoutinesRoutineIdRouteRouteWithChildren;
  "/settings/categories": typeof _protectedSettingsCategoriesRouteRouteWithChildren;
  "/timer/$taskId": typeof _protectedTimerTaskIdRouteRouteWithChildren;
  "/activities/new": typeof _protectedActivitiesNewRoute;
  "/history/new": typeof _protectedHistoryNewRoute;
  "/routines/new": typeof _protectedRoutinesNewRoute;
  "/settings/account": typeof _protectedSettingsAccountRoute;
  "/settings/notifications": typeof _protectedSettingsNotificationsRoute;
  "/timer/new": typeof _protectedTimerNewRoute;
  "/excel": typeof _protectedExcelIndexRoute;
  "/settings/": typeof _protectedSettingsIndexRoute;
  "/timer/": typeof _protectedTimerIndexRoute;
  "/settings/categories/$categoryId": typeof _protectedSettingsCategoriesCategoryIdRouteRouteWithChildren;
  "/activities/$activityId/delete": typeof _protectedActivitiesActivityIdDeleteRoute;
  "/activities/$activityId/edit": typeof _protectedActivitiesActivityIdEditRoute;
  "/routines/$routineId/delete": typeof _protectedRoutinesRoutineIdDeleteRoute;
  "/routines/$routineId/edit": typeof _protectedRoutinesRoutineIdEditRoute;
  "/settings/categories/new": typeof _protectedSettingsCategoriesNewRoute;
  "/timer/$taskId/edit": typeof _protectedTimerTaskIdEditRoute;
  "/activities/$activityId/": typeof _protectedActivitiesActivityIdIndexRoute;
  "/history/$taskId/": typeof _protectedHistoryTaskIdIndexRoute;
  "/settings/categories/$categoryId/delete": typeof _protectedSettingsCategoriesCategoryIdDeleteRoute;
  "/settings/categories/$categoryId/edit": typeof _protectedSettingsCategoriesCategoryIdEditRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/activities": typeof _protectedActivitiesRouteRouteWithChildren;
  "/history": typeof _protectedHistoryRouteRouteWithChildren;
  "/routines": typeof _protectedRoutinesRouteRouteWithChildren;
  "/": typeof _protectedIndexRoute;
  "/routines/$routineId": typeof _protectedRoutinesRoutineIdRouteRouteWithChildren;
  "/settings/categories": typeof _protectedSettingsCategoriesRouteRouteWithChildren;
  "/timer/$taskId": typeof _protectedTimerTaskIdRouteRouteWithChildren;
  "/activities/new": typeof _protectedActivitiesNewRoute;
  "/history/new": typeof _protectedHistoryNewRoute;
  "/routines/new": typeof _protectedRoutinesNewRoute;
  "/settings/account": typeof _protectedSettingsAccountRoute;
  "/settings/notifications": typeof _protectedSettingsNotificationsRoute;
  "/timer/new": typeof _protectedTimerNewRoute;
  "/excel": typeof _protectedExcelIndexRoute;
  "/settings": typeof _protectedSettingsIndexRoute;
  "/timer": typeof _protectedTimerIndexRoute;
  "/settings/categories/$categoryId": typeof _protectedSettingsCategoriesCategoryIdRouteRouteWithChildren;
  "/activities/$activityId/delete": typeof _protectedActivitiesActivityIdDeleteRoute;
  "/activities/$activityId/edit": typeof _protectedActivitiesActivityIdEditRoute;
  "/routines/$routineId/delete": typeof _protectedRoutinesRoutineIdDeleteRoute;
  "/routines/$routineId/edit": typeof _protectedRoutinesRoutineIdEditRoute;
  "/settings/categories/new": typeof _protectedSettingsCategoriesNewRoute;
  "/timer/$taskId/edit": typeof _protectedTimerTaskIdEditRoute;
  "/activities/$activityId": typeof _protectedActivitiesActivityIdIndexRoute;
  "/history/$taskId": typeof _protectedHistoryTaskIdIndexRoute;
  "/settings/categories/$categoryId/delete": typeof _protectedSettingsCategoriesCategoryIdDeleteRoute;
  "/settings/categories/$categoryId/edit": typeof _protectedSettingsCategoriesCategoryIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/__protected": typeof _protectedRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/__protected/activities": typeof _protectedActivitiesRouteRouteWithChildren;
  "/__protected/history": typeof _protectedHistoryRouteRouteWithChildren;
  "/__protected/routines": typeof _protectedRoutinesRouteRouteWithChildren;
  "/__protected/settings": typeof _protectedSettingsRouteRouteWithChildren;
  "/__protected/timer": typeof _protectedTimerRouteRouteWithChildren;
  "/__protected/": typeof _protectedIndexRoute;
  "/__protected/activities/$activityId": typeof _protectedActivitiesActivityIdRouteRouteWithChildren;
  "/__protected/history/$taskId": typeof _protectedHistoryTaskIdRouteRouteWithChildren;
  "/__protected/routines/$routineId": typeof _protectedRoutinesRoutineIdRouteRouteWithChildren;
  "/__protected/settings/categories": typeof _protectedSettingsCategoriesRouteRouteWithChildren;
  "/__protected/timer/$taskId": typeof _protectedTimerTaskIdRouteRouteWithChildren;
  "/__protected/activities/new": typeof _protectedActivitiesNewRoute;
  "/__protected/history/new": typeof _protectedHistoryNewRoute;
  "/__protected/routines/new": typeof _protectedRoutinesNewRoute;
  "/__protected/settings/account": typeof _protectedSettingsAccountRoute;
  "/__protected/settings/notifications": typeof _protectedSettingsNotificationsRoute;
  "/__protected/timer/new": typeof _protectedTimerNewRoute;
  "/__protected/excel/": typeof _protectedExcelIndexRoute;
  "/__protected/settings/": typeof _protectedSettingsIndexRoute;
  "/__protected/timer/": typeof _protectedTimerIndexRoute;
  "/__protected/settings/categories/$categoryId": typeof _protectedSettingsCategoriesCategoryIdRouteRouteWithChildren;
  "/__protected/activities/$activityId/delete": typeof _protectedActivitiesActivityIdDeleteRoute;
  "/__protected/activities/$activityId/edit": typeof _protectedActivitiesActivityIdEditRoute;
  "/__protected/routines/$routineId/delete": typeof _protectedRoutinesRoutineIdDeleteRoute;
  "/__protected/routines/$routineId/edit": typeof _protectedRoutinesRoutineIdEditRoute;
  "/__protected/settings/categories/new": typeof _protectedSettingsCategoriesNewRoute;
  "/__protected/timer/$taskId/edit": typeof _protectedTimerTaskIdEditRoute;
  "/__protected/activities/$activityId/": typeof _protectedActivitiesActivityIdIndexRoute;
  "/__protected/history/$taskId/": typeof _protectedHistoryTaskIdIndexRoute;
  "/__protected/settings/categories/$categoryId/delete": typeof _protectedSettingsCategoriesCategoryIdDeleteRoute;
  "/__protected/settings/categories/$categoryId/edit": typeof _protectedSettingsCategoriesCategoryIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/login"
    | "/activities"
    | "/history"
    | "/routines"
    | "/settings"
    | "/timer"
    | "/"
    | "/activities/$activityId"
    | "/history/$taskId"
    | "/routines/$routineId"
    | "/settings/categories"
    | "/timer/$taskId"
    | "/activities/new"
    | "/history/new"
    | "/routines/new"
    | "/settings/account"
    | "/settings/notifications"
    | "/timer/new"
    | "/excel"
    | "/settings/"
    | "/timer/"
    | "/settings/categories/$categoryId"
    | "/activities/$activityId/delete"
    | "/activities/$activityId/edit"
    | "/routines/$routineId/delete"
    | "/routines/$routineId/edit"
    | "/settings/categories/new"
    | "/timer/$taskId/edit"
    | "/activities/$activityId/"
    | "/history/$taskId/"
    | "/settings/categories/$categoryId/delete"
    | "/settings/categories/$categoryId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/activities"
    | "/history"
    | "/routines"
    | "/"
    | "/routines/$routineId"
    | "/settings/categories"
    | "/timer/$taskId"
    | "/activities/new"
    | "/history/new"
    | "/routines/new"
    | "/settings/account"
    | "/settings/notifications"
    | "/timer/new"
    | "/excel"
    | "/settings"
    | "/timer"
    | "/settings/categories/$categoryId"
    | "/activities/$activityId/delete"
    | "/activities/$activityId/edit"
    | "/routines/$routineId/delete"
    | "/routines/$routineId/edit"
    | "/settings/categories/new"
    | "/timer/$taskId/edit"
    | "/activities/$activityId"
    | "/history/$taskId"
    | "/settings/categories/$categoryId/delete"
    | "/settings/categories/$categoryId/edit";
  id:
    | "__root__"
    | "/__protected"
    | "/login"
    | "/__protected/activities"
    | "/__protected/history"
    | "/__protected/routines"
    | "/__protected/settings"
    | "/__protected/timer"
    | "/__protected/"
    | "/__protected/activities/$activityId"
    | "/__protected/history/$taskId"
    | "/__protected/routines/$routineId"
    | "/__protected/settings/categories"
    | "/__protected/timer/$taskId"
    | "/__protected/activities/new"
    | "/__protected/history/new"
    | "/__protected/routines/new"
    | "/__protected/settings/account"
    | "/__protected/settings/notifications"
    | "/__protected/timer/new"
    | "/__protected/excel/"
    | "/__protected/settings/"
    | "/__protected/timer/"
    | "/__protected/settings/categories/$categoryId"
    | "/__protected/activities/$activityId/delete"
    | "/__protected/activities/$activityId/edit"
    | "/__protected/routines/$routineId/delete"
    | "/__protected/routines/$routineId/edit"
    | "/__protected/settings/categories/new"
    | "/__protected/timer/$taskId/edit"
    | "/__protected/activities/$activityId/"
    | "/__protected/history/$taskId/"
    | "/__protected/settings/categories/$categoryId/delete"
    | "/__protected/settings/categories/$categoryId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  _protectedRouteRoute: typeof _protectedRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/__protected": {
      id: "/__protected";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof _protectedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/__protected/": {
      id: "/__protected/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof _protectedIndexRouteImport;
      parentRoute: typeof _protectedRouteRoute;
    };
    "/__protected/timer": {
      id: "/__protected/timer";
      path: "/timer";
      fullPath: "/timer";
      preLoaderRoute: typeof _protectedTimerRouteRouteImport;
      parentRoute: typeof _protectedRouteRoute;
    };
    "/__protected/settings": {
      id: "/__protected/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof _protectedSettingsRouteRouteImport;
      parentRoute: typeof _protectedRouteRoute;
    };
    "/__protected/routines": {
      id: "/__protected/routines";
      path: "/routines";
      fullPath: "/routines";
      preLoaderRoute: typeof _protectedRoutinesRouteRouteImport;
      parentRoute: typeof _protectedRouteRoute;
    };
    "/__protected/history": {
      id: "/__protected/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof _protectedHistoryRouteRouteImport;
      parentRoute: typeof _protectedRouteRoute;
    };
    "/__protected/activities": {
      id: "/__protected/activities";
      path: "/activities";
      fullPath: "/activities";
      preLoaderRoute: typeof _protectedActivitiesRouteRouteImport;
      parentRoute: typeof _protectedRouteRoute;
    };
    "/__protected/timer/": {
      id: "/__protected/timer/";
      path: "/";
      fullPath: "/timer/";
      preLoaderRoute: typeof _protectedTimerIndexRouteImport;
      parentRoute: typeof _protectedTimerRouteRoute;
    };
    "/__protected/settings/": {
      id: "/__protected/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof _protectedSettingsIndexRouteImport;
      parentRoute: typeof _protectedSettingsRouteRoute;
    };
    "/__protected/excel/": {
      id: "/__protected/excel/";
      path: "/excel";
      fullPath: "/excel";
      preLoaderRoute: typeof _protectedExcelIndexRouteImport;
      parentRoute: typeof _protectedRouteRoute;
    };
    "/__protected/timer/new": {
      id: "/__protected/timer/new";
      path: "/new";
      fullPath: "/timer/new";
      preLoaderRoute: typeof _protectedTimerNewRouteImport;
      parentRoute: typeof _protectedTimerRouteRoute;
    };
    "/__protected/settings/notifications": {
      id: "/__protected/settings/notifications";
      path: "/notifications";
      fullPath: "/settings/notifications";
      preLoaderRoute: typeof _protectedSettingsNotificationsRouteImport;
      parentRoute: typeof _protectedSettingsRouteRoute;
    };
    "/__protected/settings/account": {
      id: "/__protected/settings/account";
      path: "/account";
      fullPath: "/settings/account";
      preLoaderRoute: typeof _protectedSettingsAccountRouteImport;
      parentRoute: typeof _protectedSettingsRouteRoute;
    };
    "/__protected/routines/new": {
      id: "/__protected/routines/new";
      path: "/new";
      fullPath: "/routines/new";
      preLoaderRoute: typeof _protectedRoutinesNewRouteImport;
      parentRoute: typeof _protectedRoutinesRouteRoute;
    };
    "/__protected/history/new": {
      id: "/__protected/history/new";
      path: "/new";
      fullPath: "/history/new";
      preLoaderRoute: typeof _protectedHistoryNewRouteImport;
      parentRoute: typeof _protectedHistoryRouteRoute;
    };
    "/__protected/activities/new": {
      id: "/__protected/activities/new";
      path: "/new";
      fullPath: "/activities/new";
      preLoaderRoute: typeof _protectedActivitiesNewRouteImport;
      parentRoute: typeof _protectedActivitiesRouteRoute;
    };
    "/__protected/timer/$taskId": {
      id: "/__protected/timer/$taskId";
      path: "/$taskId";
      fullPath: "/timer/$taskId";
      preLoaderRoute: typeof _protectedTimerTaskIdRouteRouteImport;
      parentRoute: typeof _protectedTimerRouteRoute;
    };
    "/__protected/settings/categories": {
      id: "/__protected/settings/categories";
      path: "/categories";
      fullPath: "/settings/categories";
      preLoaderRoute: typeof _protectedSettingsCategoriesRouteRouteImport;
      parentRoute: typeof _protectedSettingsRouteRoute;
    };
    "/__protected/routines/$routineId": {
      id: "/__protected/routines/$routineId";
      path: "/$routineId";
      fullPath: "/routines/$routineId";
      preLoaderRoute: typeof _protectedRoutinesRoutineIdRouteRouteImport;
      parentRoute: typeof _protectedRoutinesRouteRoute;
    };
    "/__protected/history/$taskId": {
      id: "/__protected/history/$taskId";
      path: "/$taskId";
      fullPath: "/history/$taskId";
      preLoaderRoute: typeof _protectedHistoryTaskIdRouteRouteImport;
      parentRoute: typeof _protectedHistoryRouteRoute;
    };
    "/__protected/activities/$activityId": {
      id: "/__protected/activities/$activityId";
      path: "/$activityId";
      fullPath: "/activities/$activityId";
      preLoaderRoute: typeof _protectedActivitiesActivityIdRouteRouteImport;
      parentRoute: typeof _protectedActivitiesRouteRoute;
    };
    "/__protected/history/$taskId/": {
      id: "/__protected/history/$taskId/";
      path: "/";
      fullPath: "/history/$taskId/";
      preLoaderRoute: typeof _protectedHistoryTaskIdIndexRouteImport;
      parentRoute: typeof _protectedHistoryTaskIdRouteRoute;
    };
    "/__protected/activities/$activityId/": {
      id: "/__protected/activities/$activityId/";
      path: "/";
      fullPath: "/activities/$activityId/";
      preLoaderRoute: typeof _protectedActivitiesActivityIdIndexRouteImport;
      parentRoute: typeof _protectedActivitiesActivityIdRouteRoute;
    };
    "/__protected/timer/$taskId/edit": {
      id: "/__protected/timer/$taskId/edit";
      path: "/edit";
      fullPath: "/timer/$taskId/edit";
      preLoaderRoute: typeof _protectedTimerTaskIdEditRouteImport;
      parentRoute: typeof _protectedTimerTaskIdRouteRoute;
    };
    "/__protected/settings/categories/new": {
      id: "/__protected/settings/categories/new";
      path: "/new";
      fullPath: "/settings/categories/new";
      preLoaderRoute: typeof _protectedSettingsCategoriesNewRouteImport;
      parentRoute: typeof _protectedSettingsCategoriesRouteRoute;
    };
    "/__protected/routines/$routineId/edit": {
      id: "/__protected/routines/$routineId/edit";
      path: "/edit";
      fullPath: "/routines/$routineId/edit";
      preLoaderRoute: typeof _protectedRoutinesRoutineIdEditRouteImport;
      parentRoute: typeof _protectedRoutinesRoutineIdRouteRoute;
    };
    "/__protected/routines/$routineId/delete": {
      id: "/__protected/routines/$routineId/delete";
      path: "/delete";
      fullPath: "/routines/$routineId/delete";
      preLoaderRoute: typeof _protectedRoutinesRoutineIdDeleteRouteImport;
      parentRoute: typeof _protectedRoutinesRoutineIdRouteRoute;
    };
    "/__protected/activities/$activityId/edit": {
      id: "/__protected/activities/$activityId/edit";
      path: "/edit";
      fullPath: "/activities/$activityId/edit";
      preLoaderRoute: typeof _protectedActivitiesActivityIdEditRouteImport;
      parentRoute: typeof _protectedActivitiesActivityIdRouteRoute;
    };
    "/__protected/activities/$activityId/delete": {
      id: "/__protected/activities/$activityId/delete";
      path: "/delete";
      fullPath: "/activities/$activityId/delete";
      preLoaderRoute: typeof _protectedActivitiesActivityIdDeleteRouteImport;
      parentRoute: typeof _protectedActivitiesActivityIdRouteRoute;
    };
    "/__protected/settings/categories/$categoryId": {
      id: "/__protected/settings/categories/$categoryId";
      path: "/$categoryId";
      fullPath: "/settings/categories/$categoryId";
      preLoaderRoute: typeof _protectedSettingsCategoriesCategoryIdRouteRouteImport;
      parentRoute: typeof _protectedSettingsCategoriesRouteRoute;
    };
    "/__protected/settings/categories/$categoryId/edit": {
      id: "/__protected/settings/categories/$categoryId/edit";
      path: "/edit";
      fullPath: "/settings/categories/$categoryId/edit";
      preLoaderRoute: typeof _protectedSettingsCategoriesCategoryIdEditRouteImport;
      parentRoute: typeof _protectedSettingsCategoriesCategoryIdRouteRoute;
    };
    "/__protected/settings/categories/$categoryId/delete": {
      id: "/__protected/settings/categories/$categoryId/delete";
      path: "/delete";
      fullPath: "/settings/categories/$categoryId/delete";
      preLoaderRoute: typeof _protectedSettingsCategoriesCategoryIdDeleteRouteImport;
      parentRoute: typeof _protectedSettingsCategoriesCategoryIdRouteRoute;
    };
  }
}

interface _protectedActivitiesActivityIdRouteRouteChildren {
  _protectedActivitiesActivityIdDeleteRoute: typeof _protectedActivitiesActivityIdDeleteRoute;
  _protectedActivitiesActivityIdEditRoute: typeof _protectedActivitiesActivityIdEditRoute;
  _protectedActivitiesActivityIdIndexRoute: typeof _protectedActivitiesActivityIdIndexRoute;
}

const _protectedActivitiesActivityIdRouteRouteChildren: _protectedActivitiesActivityIdRouteRouteChildren =
  {
    _protectedActivitiesActivityIdDeleteRoute:
      _protectedActivitiesActivityIdDeleteRoute,
    _protectedActivitiesActivityIdEditRoute:
      _protectedActivitiesActivityIdEditRoute,
    _protectedActivitiesActivityIdIndexRoute:
      _protectedActivitiesActivityIdIndexRoute,
  };

const _protectedActivitiesActivityIdRouteRouteWithChildren =
  _protectedActivitiesActivityIdRouteRoute._addFileChildren(
    _protectedActivitiesActivityIdRouteRouteChildren,
  );

interface _protectedActivitiesRouteRouteChildren {
  _protectedActivitiesActivityIdRouteRoute: typeof _protectedActivitiesActivityIdRouteRouteWithChildren;
  _protectedActivitiesNewRoute: typeof _protectedActivitiesNewRoute;
}

const _protectedActivitiesRouteRouteChildren: _protectedActivitiesRouteRouteChildren =
  {
    _protectedActivitiesActivityIdRouteRoute:
      _protectedActivitiesActivityIdRouteRouteWithChildren,
    _protectedActivitiesNewRoute: _protectedActivitiesNewRoute,
  };

const _protectedActivitiesRouteRouteWithChildren =
  _protectedActivitiesRouteRoute._addFileChildren(
    _protectedActivitiesRouteRouteChildren,
  );

interface _protectedHistoryTaskIdRouteRouteChildren {
  _protectedHistoryTaskIdIndexRoute: typeof _protectedHistoryTaskIdIndexRoute;
}

const _protectedHistoryTaskIdRouteRouteChildren: _protectedHistoryTaskIdRouteRouteChildren =
  {
    _protectedHistoryTaskIdIndexRoute: _protectedHistoryTaskIdIndexRoute,
  };

const _protectedHistoryTaskIdRouteRouteWithChildren =
  _protectedHistoryTaskIdRouteRoute._addFileChildren(
    _protectedHistoryTaskIdRouteRouteChildren,
  );

interface _protectedHistoryRouteRouteChildren {
  _protectedHistoryTaskIdRouteRoute: typeof _protectedHistoryTaskIdRouteRouteWithChildren;
  _protectedHistoryNewRoute: typeof _protectedHistoryNewRoute;
}

const _protectedHistoryRouteRouteChildren: _protectedHistoryRouteRouteChildren =
  {
    _protectedHistoryTaskIdRouteRoute:
      _protectedHistoryTaskIdRouteRouteWithChildren,
    _protectedHistoryNewRoute: _protectedHistoryNewRoute,
  };

const _protectedHistoryRouteRouteWithChildren =
  _protectedHistoryRouteRoute._addFileChildren(
    _protectedHistoryRouteRouteChildren,
  );

interface _protectedRoutinesRoutineIdRouteRouteChildren {
  _protectedRoutinesRoutineIdDeleteRoute: typeof _protectedRoutinesRoutineIdDeleteRoute;
  _protectedRoutinesRoutineIdEditRoute: typeof _protectedRoutinesRoutineIdEditRoute;
}

const _protectedRoutinesRoutineIdRouteRouteChildren: _protectedRoutinesRoutineIdRouteRouteChildren =
  {
    _protectedRoutinesRoutineIdDeleteRoute:
      _protectedRoutinesRoutineIdDeleteRoute,
    _protectedRoutinesRoutineIdEditRoute: _protectedRoutinesRoutineIdEditRoute,
  };

const _protectedRoutinesRoutineIdRouteRouteWithChildren =
  _protectedRoutinesRoutineIdRouteRoute._addFileChildren(
    _protectedRoutinesRoutineIdRouteRouteChildren,
  );

interface _protectedRoutinesRouteRouteChildren {
  _protectedRoutinesRoutineIdRouteRoute: typeof _protectedRoutinesRoutineIdRouteRouteWithChildren;
  _protectedRoutinesNewRoute: typeof _protectedRoutinesNewRoute;
}

const _protectedRoutinesRouteRouteChildren: _protectedRoutinesRouteRouteChildren =
  {
    _protectedRoutinesRoutineIdRouteRoute:
      _protectedRoutinesRoutineIdRouteRouteWithChildren,
    _protectedRoutinesNewRoute: _protectedRoutinesNewRoute,
  };

const _protectedRoutinesRouteRouteWithChildren =
  _protectedRoutinesRouteRoute._addFileChildren(
    _protectedRoutinesRouteRouteChildren,
  );

interface _protectedSettingsCategoriesCategoryIdRouteRouteChildren {
  _protectedSettingsCategoriesCategoryIdDeleteRoute: typeof _protectedSettingsCategoriesCategoryIdDeleteRoute;
  _protectedSettingsCategoriesCategoryIdEditRoute: typeof _protectedSettingsCategoriesCategoryIdEditRoute;
}

const _protectedSettingsCategoriesCategoryIdRouteRouteChildren: _protectedSettingsCategoriesCategoryIdRouteRouteChildren =
  {
    _protectedSettingsCategoriesCategoryIdDeleteRoute:
      _protectedSettingsCategoriesCategoryIdDeleteRoute,
    _protectedSettingsCategoriesCategoryIdEditRoute:
      _protectedSettingsCategoriesCategoryIdEditRoute,
  };

const _protectedSettingsCategoriesCategoryIdRouteRouteWithChildren =
  _protectedSettingsCategoriesCategoryIdRouteRoute._addFileChildren(
    _protectedSettingsCategoriesCategoryIdRouteRouteChildren,
  );

interface _protectedSettingsCategoriesRouteRouteChildren {
  _protectedSettingsCategoriesCategoryIdRouteRoute: typeof _protectedSettingsCategoriesCategoryIdRouteRouteWithChildren;
  _protectedSettingsCategoriesNewRoute: typeof _protectedSettingsCategoriesNewRoute;
}

const _protectedSettingsCategoriesRouteRouteChildren: _protectedSettingsCategoriesRouteRouteChildren =
  {
    _protectedSettingsCategoriesCategoryIdRouteRoute:
      _protectedSettingsCategoriesCategoryIdRouteRouteWithChildren,
    _protectedSettingsCategoriesNewRoute: _protectedSettingsCategoriesNewRoute,
  };

const _protectedSettingsCategoriesRouteRouteWithChildren =
  _protectedSettingsCategoriesRouteRoute._addFileChildren(
    _protectedSettingsCategoriesRouteRouteChildren,
  );

interface _protectedSettingsRouteRouteChildren {
  _protectedSettingsCategoriesRouteRoute: typeof _protectedSettingsCategoriesRouteRouteWithChildren;
  _protectedSettingsAccountRoute: typeof _protectedSettingsAccountRoute;
  _protectedSettingsNotificationsRoute: typeof _protectedSettingsNotificationsRoute;
  _protectedSettingsIndexRoute: typeof _protectedSettingsIndexRoute;
}

const _protectedSettingsRouteRouteChildren: _protectedSettingsRouteRouteChildren =
  {
    _protectedSettingsCategoriesRouteRoute:
      _protectedSettingsCategoriesRouteRouteWithChildren,
    _protectedSettingsAccountRoute: _protectedSettingsAccountRoute,
    _protectedSettingsNotificationsRoute: _protectedSettingsNotificationsRoute,
    _protectedSettingsIndexRoute: _protectedSettingsIndexRoute,
  };

const _protectedSettingsRouteRouteWithChildren =
  _protectedSettingsRouteRoute._addFileChildren(
    _protectedSettingsRouteRouteChildren,
  );

interface _protectedTimerTaskIdRouteRouteChildren {
  _protectedTimerTaskIdEditRoute: typeof _protectedTimerTaskIdEditRoute;
}

const _protectedTimerTaskIdRouteRouteChildren: _protectedTimerTaskIdRouteRouteChildren =
  {
    _protectedTimerTaskIdEditRoute: _protectedTimerTaskIdEditRoute,
  };

const _protectedTimerTaskIdRouteRouteWithChildren =
  _protectedTimerTaskIdRouteRoute._addFileChildren(
    _protectedTimerTaskIdRouteRouteChildren,
  );

interface _protectedTimerRouteRouteChildren {
  _protectedTimerTaskIdRouteRoute: typeof _protectedTimerTaskIdRouteRouteWithChildren;
  _protectedTimerNewRoute: typeof _protectedTimerNewRoute;
  _protectedTimerIndexRoute: typeof _protectedTimerIndexRoute;
}

const _protectedTimerRouteRouteChildren: _protectedTimerRouteRouteChildren = {
  _protectedTimerTaskIdRouteRoute: _protectedTimerTaskIdRouteRouteWithChildren,
  _protectedTimerNewRoute: _protectedTimerNewRoute,
  _protectedTimerIndexRoute: _protectedTimerIndexRoute,
};

const _protectedTimerRouteRouteWithChildren =
  _protectedTimerRouteRoute._addFileChildren(_protectedTimerRouteRouteChildren);

interface _protectedRouteRouteChildren {
  _protectedActivitiesRouteRoute: typeof _protectedActivitiesRouteRouteWithChildren;
  _protectedHistoryRouteRoute: typeof _protectedHistoryRouteRouteWithChildren;
  _protectedRoutinesRouteRoute: typeof _protectedRoutinesRouteRouteWithChildren;
  _protectedSettingsRouteRoute: typeof _protectedSettingsRouteRouteWithChildren;
  _protectedTimerRouteRoute: typeof _protectedTimerRouteRouteWithChildren;
  _protectedIndexRoute: typeof _protectedIndexRoute;
  _protectedExcelIndexRoute: typeof _protectedExcelIndexRoute;
}

const _protectedRouteRouteChildren: _protectedRouteRouteChildren = {
  _protectedActivitiesRouteRoute: _protectedActivitiesRouteRouteWithChildren,
  _protectedHistoryRouteRoute: _protectedHistoryRouteRouteWithChildren,
  _protectedRoutinesRouteRoute: _protectedRoutinesRouteRouteWithChildren,
  _protectedSettingsRouteRoute: _protectedSettingsRouteRouteWithChildren,
  _protectedTimerRouteRoute: _protectedTimerRouteRouteWithChildren,
  _protectedIndexRoute: _protectedIndexRoute,
  _protectedExcelIndexRoute: _protectedExcelIndexRoute,
};

const _protectedRouteRouteWithChildren = _protectedRouteRoute._addFileChildren(
  _protectedRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  _protectedRouteRoute: _protectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
