name: Dependabot CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    if: github.actor == 'dependabot[bot]' # Run only for Dependabot PRs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - run: npm run prettier
      - run: npm run lint
      - run: npm run test
